version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    # Look for `build.gradle.kts` file in the `root` directory
    directory: "/"
    # Check the registry for updates every day (weekdays)
    schedule:
      interval: "daily"